<?php

/**
 * This class is responsible for generating emails that are then sent to users.
 * 
 * The emails generated by this class contain simple information
 */
class Cbcoverseas_Digest_EmailFactory implements Evan_Email_MessageFactory {
    
    const LAST_NOTIFIED_METADATA = 'cbc_last_digest_time';

    public function __construct(Evan_Clock $clock, ElggSite $site, Evan_ViewService $views, Evan_Db $db, Evan_I18n $i18n) {
        $this->clock = $clock;
        $this->site = $site;
        $this->views = $views;
        $this->db = $db;
        $this->i18n = $i18n;
    }    
    
    /**
     * @param int $limit The maximum number of users to return.
     * 
     * @return ElggUser[] A list of users to send the digest to.
     */
    public function getUsers($limit) {
        $users = $this->getNeverNotifiedUsers($limit);
        
	// If we have leftover quota, use it on the least recently notified users.
        $limit -= count($users);
        if ($limit > 0) {
            $users = array_merge($users, $this->getLeastRecentlyNotifiedUsers($limit));
        }
        
        return $users;
    }
    
    /**
     * @param int $limit The maximum number of users to return.
     * 
     * @return ElggUser[] A list of users that have never been sent this digest.
     */
    private function getNeverNotifiedUsers($limit) {
        $dbprefix = $this->db->getPrefix();
        $name_metastring_id = $this->db->addMetastring('cbc_last_digest_time');

        return $this->db->getEntities(array(
            'type' => 'user',
            'wheres' => array("NOT EXISTS (
                SELECT 1 FROM {$dbprefix}metadata md
                WHERE md.entity_guid = e.guid
                    AND md.name_id = $name_metastring_id)"),
            'limit' => $limit,
        ));
    }
    
    /**
     * @param int $limit The maximum number of users to return.
     * 
     * @return ElggUser[] A list of users that have least-recently received the digest.
     */
    private function getLeastRecentlyNotifiedUsers($limit) {
        return $this->db->getEntities(array(
            'type' => 'user',
            'order_by_metadata' => array(
                'name' => 'cbc_last_digest_time',
                'direction' => 'asc',
                'as' => 'integer',
            ),
            'limit' => $limit,
        ));
    }
     
    private function getSubject(ElggUser $user) {
        $date = $this->clock->getDateTime()->format('M j, Y');
        
        return $this->i18n->translate("New activity on %s", array($date), $user->language);
    }
    
    private function getBody(ElggUser $user, $activities) {
        $vars = array_merge($activities, array(
            'site' => $this->site,
            'user' => $user,
        ));
        
        // TODO(ewinslow): Make this i18n'able somehow
        return $this->views->view('cbcoverseas/digest.en', $vars, 'email');
    }
    
    private function getActivities(ElggUser $user) {
        $results = array();
        
        $last_digest_time = $this->getLastDigestTime($user);
        
        $results['blogs'] = $this->db->getEntities(array(
            'type' => 'object',
            'subtype' => 'blog',
            'created_time_lower' => $last_digest_time,
            'count' => true,
        ));
        
        $results['photos'] = $this->db->getEntities(array(
            'type' => 'object',
            'subtype' => 'image',
            'created_time_lower' => $last_digest_time,
            'count' => true,
        ));
        
        return $results;
    }
    
    private function getLastDigestTime(ElggUser $user) {
        // Initialize the last digest time if it hasn't yet been set.
        if (!isset($user->cbc_last_digest_time)) {
            if ($user->last_login) {
                $user->cbc_last_digest_time = $user->last_login;
            } else {
                $two_weeks_ago = time() - 14 * 24 * 60 * 60;
                $user->cbc_last_digest_time = $two_weeks_ago;
            }
        }
        
        return $user->cbc_last_digest_time;
    }
    
    /** @override */
    public function createForUser(ElggUser $user) {
        $olduser = $this->db->getUser();
        $this->db->setUser($user);
        
        $activities = $this->getActivities($user);
        
        $totalActivities = array_sum(array_values($activities));
	
        // Records the last time we attempted to generate a digest for the user.
        $user->cbc_last_digest_time = $this->clock->getTimestamp();
        
	// If there's no activity, don't send an email!
        if ($totalActivities <= 0) {
            $this->db->setUser($olduser);
            return NULL;
        }
        
        $message = new Evan_Email_Message();
        
        $message->setTo($user->email)
            ->setFrom($this->site->email)
            ->setSubject($this->getSubject($user))
            ->setBody($this->getBody($user, $activities));
        
        $this->db->setUser($olduser);
        
        return $message;
    }
}
