<?php

/**
 * This class is responsible for generating emails that are then sent to users.
 * 
 * The emails generated by this class contain simple information
 */
class Cbcoverseas_Digest_EmailFactory implements Evan_Email_MessageFactory {
    
    public function __construct(Evan_Clock $clock, ElggSite $site, Evan_ViewService $views, Evan_Db $db, Evan_I18n $i18n) {
        $this->clock = $clock;
        $this->site = $site;
        $this->views = $views;
        $this->db = $db;
        $this->i18n = $i18n;
    }    
    
    private function getSubject(ElggUser $user) {
        $date = $this->clock->getDateTime()->format('M j, Y');
        
        return $this->i18n->translate("New activity on %s", array($date), $user->language);
    }
    
    private function getBody(ElggUser $user, $activities) {
        $vars = array_merge($activities, array(
            'site' => $this->site,
            'user' => $user,
        ));
        
        // TODO(ewinslow): Make this i18n'able somehow
        return $this->views->view('cbcoverseas/digest.en', $vars, 'email');
    }
    
    private function getActivities(ElggUser $user) {
        $results = array();
        
        $last_digest_time = $this->getLastDigestTime($user);
        
        $results['blogs'] = $this->db->getEntities(array(
            'type' => 'object',
            'subtype' => 'blog',
            'created_time_lower' => $last_digest_time,
            'count' => true,
        ));
        
        $results['photos'] = $this->db->getEntities(array(
            'type' => 'object',
            'subtype' => 'image',
            'created_time_lower' => $last_digest_time,
            'count' => true,
        ));
        
        return $results;
    }
    
    private function getLastDigestTime(ElggUser $user) {
        // Initialize the last digest time if it hasn't yet been set.
        if (!isset($user->cbc_last_digest_time)) {
            if ($user->last_login) {
                $user->cbc_last_digest_time = $user->last_login;
            } else {
                $two_weeks_ago = time() - 14 * 24 * 60 * 60;
                $user->cbc_last_digest_time = $two_weeks_ago;
            }
        }
        
        return $user->cbc_last_digest_time;
    }
    
    /** @override */
    public function createForUser(ElggUser $user) {
        $olduser = $this->db->getUser();
        $this->db->setUser($user);
        
        $activities = $this->getActivities($user);
        
        $totalActivities = array_sum(array_values($activities));
        
        // If there's no activity, don't send an email!
        if ($totalActivities <= 0) {
            $this->db->setUser($olduser);
            return NULL;
        }
        
        $message = new Evan_Email_Message();
        
        $message->setTo($user->email)
            ->setFrom($this->site->email)
            ->setSubject($this->getSubject($user))
            ->setBody($this->getBody($user, $activities));
            
        $this->db->setUser($olduser);
        
        return $message;
    }
}